### ISSUE TITLE
segmentation fault (when building documentation)

### ISSUE THREAD

**Issue by cqc-melf** [CQCL/pytket-projectq#77]
```
   File "<frozen runpy>", line 198 in _run_module_as_main
./.github/workflows/build-test: line 57:  1047 Segmentation fault      pytest --doctest-modules

**Comment by cqc-alec** [comment]
I think the segfault happens when running the python tests, rather than building the documentation.
Windows only it seems. Looks like the same issue as https://github.com/CQCL/pytket-pennylane/issues/125 .

**Comment by cqc-alec** [comment]
This issue seems to have gone away: recent scheduled runs on CI have succeeded.
